version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ./credentials:/app/credentials
    # --- MODIFIKASI KUNCI ---
    # Sekarang, backend akan menunggu sampai healthcheck db 'sehat'
    depends_on:
      db:
        condition: service_healthy
    # -----------------------

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker
    # --- TAMBAHAN BARU ---
    # Memberitahu Docker cara memeriksa apakah database sudah siap
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mentoradb"]
      interval: 5s
      timeout: 5s
      retries: 5
    # --------------------

volumes:
  postgres_data:
